#Project Euler Problem 2

"""

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""
import timeit                               #To time my function
start = timeit.default_timer()

a, b = 0, 1
i = 0

while True:

    a, b = b, a + b
    if b > 4e6:
        break
    elif b % 2 == 0:
        i = i + b
print (i)
    
stop = timeit.default_timer()
print ("Script runtime was " + str((stop - start) * 1000) + " ms.") 
